### ISSUE TITLE
這個好難。其實不會

### ISSUE THREAD

**Issue by Larisa-HSU** [Larisa-HSU/SCU_Python_Learning#21]
小仔養豬
Description

小仔害怕吃到外面不乾淨的豬肉，所以決定自己經營一間養豬場，小仔第一次養豬好多事情不太懂，但他有上課聽到老師說過養豬場的控溫很重要，養豬業有一句話是說「小豬怕冷、母豬怕熱」，母豬的體溫較小豬高，所以當早上進入豬場發現小豬幾乎都躺在母豬四周，就表示小豬覺得環境溫度太低，這時要必須調高養豬場環境溫度，否則就會影響小豬育成率。小仔已經在養豬場四周放置監測工具，並有一個自己判斷密集度的演算法，請用他的方法幫他寫出一段程式從數據判斷是否養豬場的環境溫度合適吧！

假設養豬場為一個二維平面，題目給定 x, y，則養豬場是從座標平面上

(0, 0)、(x, 0)、(0, y)、(x, y) 四個角落點所圍成的矩形區域中，題目給定表示點 (i, j) 上的數值，若為 0，則點 (i, j) 為養豬場母豬所在點；若為正整數，數字則表示為在點(i, j)上小豬的數目。題目給定四周距離r，若母豬點 (u, v) 和小豬點 (i, j) 滿足以下公式，則判定小豬點(i, j)在母豬點(u, v)的四周。

![image](https://user-images.githubusercontent.com/80834757/113112909-4d72e300-923c-11eb-9562-46a541de2bae.png)

題目再給定密集度d %，並已知以下判斷小豬是否過於靠近母豬的公式

![image](https://user-images.githubusercontent.com/80834757/113112951-5bc0ff00-923c-11eb-879a-f8e52208559a.png)

若養豬場所有母豬皆不符合以上公式，則環境溫度正常，反之，環境溫度太低。

Input
共有 y + 2 行，

第 1 行，有四個正整數，x, y, r, d，分別代表養豬場 x 座標上界、養豬場 y 座標上界、四周距離、密集度，中間以空白隔開。

第 2 行，到 y + 2 行各有 x + 1 個正整數，代表點(i, j)上的數字，中間以半形空白隔開，若為 0 ，則為養豬場母豬所在點；若為正整數，則表示為小豬的數目。

Output
共2行，

第1行，輸出養豬場中母豬的總數量和小豬的總數量，中間以半形逗號隔開。

第2行，輸出養豬場環境溫度是否合適，太低輸出 0，合適輸出 1。

Sample Input 1 
3 3 1 50
4 7 6 1
3 0 3 1
9 3 2 1
1 5 7 3

Sample Output 1
1,56
1

Sample Input 2 
4 3 1 40
2 5 1 4 3
0 1 20 5 7
2 3 0 10 1
3 4 9 2 1

Sample Output 2
2,83
0
Hint

輸入解釋，以 sample 1 為例，

輸入第一行 ，分別為養豬場 x 座標上界、養豬場 y 座標上界、四周距離、密集度

輸入第二行，代表座標平面點(0,0)、(0,1).....(0,3)上的數值，因為皆為正整數所以代表是小豬的數目，

輸入第三行，代表座標平面點(1,0)、(1,1).....(1,3)上的數值，其中點(1,1)數值是 0 ，所以代表母豬所在地

........

總共輸入有3+2行

**Comment by Li-Wei-Hsiao** [comment]
所以不難?
